# Travis will use Ruby version specified in `.ruby-version`
language: ruby
bundler_args: --without production
before_script:
  - psql -c 'CREATE DATABASE ahoy_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
