# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfbdc438bee424801ce6c5ef6ec2be0130546da558e63266ebb13ef2794f667e5a9effd284547fe9bbf3485abe3666a4a3d8354b6233fd909c2230e22e589ea4

test:
  secret_key_base: a58eaf6bceb5ad7a644a07f9c50c21bd3eb853f14bafe5fef4df55beef33ce72f3ff60855ec27bd9bbeebb9cc349f1fe2ebd886a8d7fb38629faf877c98cbd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
