common: &common
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'dfbdc438bee424801ce6c5ef6ec2be0130546da558e63266ebb13ef2794f667e5a9effd284547fe9bbf3485abe3666a4a3d8354b6233fd909c2230e22e589ea4' %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] || '339696873873-pdi1fkio15fp7vc6aii9lm8mf91mp2a7.apps.googleusercontent.com' %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] || 'YF0vMuALPLUqYQx8I98qSRCN' %>

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common
